version: '3'
services:
  redis:
    build:
      context: .
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - updater-network

networks:
  updater-network:
    driver: bridge
